// Generated by CoffeeScript 1.6.3
var empty, git, join, log, logSeq, map, previousCommitsSeq, produced, series, _ref;

git = require('gitteh-promisified');

_ref = require('reduced'), produced = _ref.produced, join = _ref.join, series = _ref.series, map = _ref.map, empty = _ref.empty;

previousCommitsSeq = function(commit) {
  var getCommit, getPreviousCommit;
  getCommit = function(id) {
    return commit.then(function(commit) {
      return commit.repository.commit(id);
    });
  };
  getPreviousCommit = function(commit) {
    var parents;
    if (commit.parents.length > 0) {
      parents = map(commit.parents, getCommit);
      return join(map(parents, previousCommitsSeq));
    } else {
      return empty();
    }
  };
  return join(series(getPreviousCommit, commit));
};

logSeq = function(ref) {
  return previousCommitsSeq(ref.repository.commit(ref.target));
};

log = function(ref) {
  return produced(logSeq(ref));
};

module.exports = {
  log: log,
  logSeq: logSeq,
  previousCommitsSeq: previousCommitsSeq
};
