// Generated by CoffeeScript 1.6.3
var equal, git, join, log, logSeq, _ref;

equal = require('assert').equal;

join = require('path').join;

git = require('gitteh-promisified');

_ref = require('./index'), log = _ref.log, logSeq = _ref.logSeq;

describe('gitteh-log', function() {
  var branch;
  branch = git.openRepository(join(__dirname, '.git')).then(function(repo) {
    return repo.reference("refs/heads/master");
  });
  return it('works', function(done) {
    return branch.then(function(branch) {
      return log(branch);
    }).then(function(log) {
      log.reverse();
      equal(log[0].id, '624558d1f88b4c0a675fb53c2cccb6baa4ba6b1c');
      return done();
    }).fail(done).end();
  });
});
